// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXinmwULQ5kUbuwO42j6sI5thtJ54DD-I',
    appId: '1:777115686075:web:615e40d9f0668a90a2459e',
    messagingSenderId: '777115686075',
    projectId: 'fruithub-946fa',
    authDomain: 'fruithub-946fa.firebaseapp.com',
    storageBucket: 'fruithub-946fa.firebasestorage.app',
    measurementId: 'G-T0QM18M4R7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXE2OpyKK29NRAxjVdcnQYa5OsPZ_epnA',
    appId: '1:777115686075:android:8a5f4922b31e4a69a2459e',
    messagingSenderId: '777115686075',
    projectId: 'fruithub-946fa',
    storageBucket: 'fruithub-946fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCES79z-HeWqY9xMEvCj8r7MFhiSrYal4Y',
    appId: '1:777115686075:ios:65902705de57894fa2459e',
    messagingSenderId: '777115686075',
    projectId: 'fruithub-946fa',
    storageBucket: 'fruithub-946fa.firebasestorage.app',
    iosBundleId: 'com.example.fruitsECommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCES79z-HeWqY9xMEvCj8r7MFhiSrYal4Y',
    appId: '1:777115686075:ios:65902705de57894fa2459e',
    messagingSenderId: '777115686075',
    projectId: 'fruithub-946fa',
    storageBucket: 'fruithub-946fa.firebasestorage.app',
    iosBundleId: 'com.example.fruitsECommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXinmwULQ5kUbuwO42j6sI5thtJ54DD-I',
    appId: '1:777115686075:web:58218fd62739641ca2459e',
    messagingSenderId: '777115686075',
    projectId: 'fruithub-946fa',
    authDomain: 'fruithub-946fa.firebaseapp.com',
    storageBucket: 'fruithub-946fa.firebasestorage.app',
    measurementId: 'G-2CPYVPFWK8',
  );
}
